### ISSUE TITLE
DatatypeConverter used by jjwt is not found

### ISSUE THREAD

**Issue by tangxinyao** [wpcfan/spring-boot-tut#7]
系统环境：Spring boot 1.5.7.RELEASE, java 9

java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[na:na]
	at io.jsonwebtoken.impl.Base64Codec.decode(Base64Codec.java:26) ~[jjwt-0.9.0.jar:0.9.0]
	at io.jsonwebtoken.impl.DefaultJwtBuilder.signWith(DefaultJwtBuilder.java:99) ~[jjwt-0.9.0.jar:0.9.0]

请问这种情况如何产生，应该如何解决？感谢~

**Comment by wpcfan** [comment]
升级 jjwt
